# Generated by Django 6.0.2 on 2026-02-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_interval_minutes', models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('entries_count', models.IntegerField()),
                ('main_file', models.CharField(max_length=255)),
                ('archive_file', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
    ]
