# Generated by Django 6.0.2 on 2026-03-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterun',
            name='dshield_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='updaterun',
            name='firehol_count',
            field=models.IntegerField(default=0),
        ),
    ]
